services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped