export { default as HomePage } from './HomePage';
export { default as FAQPage } from './FAQPage';
export { default as ErrorPage } from './ErrorPage';
export { default as AboutPage } from './AboutPage';
export * from './ChatPage';
export { default as StartUpPage } from './StartUpPage';
export { default as UserAgreePage } from './UserAgreePage';
export * from './auth';
export * from './company';
export * from './designer';
export * from './order';
